CREATE TABLE `characters` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`honor_points` integer NOT NULL,
	`hp` integer NOT NULL,
	`mp` integer NOT NULL,
	`attack` integer NOT NULL,
	`defense` integer NOT NULL,
	`magic` integer NOT NULL,
	`magic_defense` integer NOT NULL,
	`evasion` integer NOT NULL,
	`created_at` text DEFAULT (current_timestamp) NOT NULL,
	`updated_at` text DEFAULT (current_timestamp) NOT NULL,
	`user_id` text NOT NULL,
	`class_id` text NOT NULL,
	`job_id` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE cascade ON DELETE cascade,
	FOREIGN KEY (`class_id`) REFERENCES `classes`(`id`) ON UPDATE cascade ON DELETE cascade,
	FOREIGN KEY (`job_id`) REFERENCES `jobs`(`id`) ON UPDATE cascade ON DELETE cascade
);
